import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import heavyConnectInventory from "@/data/heavyconnect-reports/inventory.json";
import localPrimusSources from "@/data/primus-local/source-map.json";
import primusCrosswalk from "@/data/primusgfs/crosswalks/v3-2-to-v4-0.json";

type CrosswalkSummary = {
  strong_candidate?: number;
  review_candidate?: number;
  needs_manual_mapping?: number;
};

type PacketRequest = {
  count: number;
  generatedBy: string;
  startDate: string;
  endDate: string;
  selectedIds: number[];
};

function parsePacketRequest(input: unknown): PacketRequest | null {
  if (!input || typeof input !== "object") return null;
  const body = input as Record<string, unknown>;
  const count = Number(body.count ?? heavyConnectInventory.report_count);
  const generatedBy = typeof body.generatedBy === "string" && body.generatedBy.trim() ? body.generatedBy.trim().slice(0, 80) : "Juan Diaz";
  const startDate = typeof body.startDate === "string" && /^\d{4}-\d{2}-\d{2}$/.test(body.startDate) ? body.startDate : "2025-01-01";
  const endDate = typeof body.endDate === "string" && /^\d{4}-\d{2}-\d{2}$/.test(body.endDate) ? body.endDate : "2026-01-01";
  const selectedIds = Array.isArray(body.selectedIds) ? body.selectedIds.map(Number).filter(Number.isFinite).slice(0, 500) : [];
  if (!Number.isFinite(count) || count < 0 || count > 500) return null;
  if (new Date(startDate) > new Date(endDate)) return null;
  return { count, generatedBy, startDate, endDate, selectedIds };
}

export async function POST(request: Request) {
  let body: PacketRequest | null = null;
  try {
    body = parsePacketRequest(await request.json());
  } catch {
    body = null;
  }
  if (!body) {
    return NextResponse.json({ error: "Invalid audit packet request" }, { status: 400 });
  }

  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const page = pdf.addPage([612, 792]);
  const crosswalkSummary = primusCrosswalk.summary as CrosswalkSummary;
  const localSourceCount = localPrimusSources.module_sources.reduce((sum, module) => sum + module.source_count, 0);

  page.drawRectangle({ x: 0, y: 700, width: 612, height: 92, color: rgb(0.04, 0.18, 0.14) });
  page.drawText("BAY BABY PRODUCE", { x: 52, y: 747, size: 12, font: bold, color: rgb(0.72, 0.9, 0.69) });
  page.drawText("PrimusGFS Audit Packet", { x: 52, y: 718, size: 25, font: bold, color: rgb(1, 1, 1) });
  page.drawText(`${body.startDate} to ${body.endDate}`, { x: 52, y: 660, size: 16, font: bold });
  page.drawText(`Generated by ${body.generatedBy} - ${new Date().toLocaleDateString("en-US")}`, { x: 52, y: 636, size: 10, font, color: rgb(0.35, 0.38, 0.37) });

  const lines = [
    ["Reports included", String(body.count || heavyConnectInventory.report_count)],
    ["Selected report IDs", body.selectedIds.length ? String(body.selectedIds.length) : "All scoped reports"],
    ["Local PRIMUS source items", String(localSourceCount)],
    ["Historical standard basis", localPrimusSources.summary.historical_standard],
    ["Target standard", localPrimusSources.summary.future_standard],
    ["Bay Baby scoped modules", String(localPrimusSources.bay_baby_scope.active_module_keys.length)],
    ["Legacy question matches", String(crosswalkSummary.strong_candidate ?? 0)],
    ["Manual crosswalk review", `${crosswalkSummary.needs_manual_mapping ?? 0} questions`],
  ];

  let y = 560;
  for (const [label, value] of lines) {
    page.drawText(label, { x: 52, y, size: 12, font });
    page.drawText(value, { x: 430, y, size: 13, font: bold, color: rgb(0.07, 0.38, 0.2) });
    page.drawLine({ start: { x: 52, y: y - 12 }, end: { x: 560, y: y - 12 }, thickness: 0.5, color: rgb(0.82, 0.84, 0.82) });
    y -= 42;
  }

  page.drawText("Packet sections", { x: 52, y: 210, size: 15, font: bold });
  page.drawText("Audit summary - PrimusGFS module index - Bay Baby source evidence index", { x: 52, y: 184, size: 10, font });
  page.drawText("Corrective actions - Document control register - Traceability readiness", { x: 52, y: 165, size: 10, font });
  page.drawText("Report appendix - Attachments appendix - Signature and review log", { x: 52, y: 146, size: 10, font });
  page.drawText("Note: Local files are v3.2-era evidence; review crosswalks before official v4.0 scoring.", { x: 52, y: 102, size: 9, font, color: rgb(0.55, 0.32, 0.05) });

  const bytes = await pdf.save();
  return new NextResponse(Buffer.from(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="Bay-Baby-PrimusGFS-v4-Audit-Packet_2025-01-01_to_2026-01-01.pdf"`,
    },
  });
}
