import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import primusCrosswalk from "@/data/primusgfs/crosswalks/v3-2-to-v4-0.json";

type CrosswalkSummary = {
  strong_candidate?: number;
  review_candidate?: number;
  needs_manual_mapping?: number;
};

export async function POST(request: Request) {
  const body = await request.json();
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const page = pdf.addPage([612, 792]);
  const crosswalkSummary = primusCrosswalk.summary as CrosswalkSummary;

  page.drawRectangle({ x: 0, y: 700, width: 612, height: 92, color: rgb(0.04, 0.18, 0.14) });
  page.drawText("BAY BABY PRODUCE", { x: 52, y: 747, size: 12, font: bold, color: rgb(0.72, 0.9, 0.69) });
  page.drawText("PrimusGFS v4.0 Audit Packet", { x: 52, y: 718, size: 25, font: bold, color: rgb(1, 1, 1) });
  page.drawText(`${body.startDate ?? "Selected start"} to ${body.endDate ?? "Selected end"}`, { x: 52, y: 660, size: 16, font: bold });
  page.drawText(`Generated by ${body.generatedBy ?? "Bay Baby Audit"} - ${new Date().toLocaleDateString("en-US")}`, { x: 52, y: 636, size: 10, font, color: rgb(0.35, 0.38, 0.37) });

  const lines = [
    ["Reports included", String(body.count ?? 0)],
    ["Reviewed and approved", String(body.approvedCount ?? 0)],
    ["Still in review", String(body.reviewCount ?? 0)],
    ["Needs attention", String(body.actionCount ?? 0)],
    ["Readiness", body.readiness === undefined ? "Not calculated" : `${body.readiness}%`],
    ["Legacy question matches", String(crosswalkSummary.strong_candidate ?? 0)],
    ["Manual crosswalk review", `${crosswalkSummary.needs_manual_mapping ?? 0} questions`],
  ];

  let y = 560;
  for (const [label, value] of lines) {
    page.drawText(label, { x: 52, y, size: 12, font });
    page.drawText(value, { x: 430, y, size: 13, font: bold, color: rgb(0.07, 0.38, 0.2) });
    page.drawLine({ start: { x: 52, y: y - 12 }, end: { x: 560, y: y - 12 }, thickness: 0.5, color: rgb(0.82, 0.84, 0.82) });
    y -= 42;
  }

  page.drawText("Packet sections", { x: 52, y: 210, size: 15, font: bold });
  page.drawText("Audit summary - PrimusGFS v4.0 module index - Bay Baby evidence index", { x: 52, y: 184, size: 10, font });
  page.drawText("Exceptions and corrective actions - Report appendix - Signature and review log", { x: 52, y: 165, size: 10, font });
  page.drawText("Note: Crosswalk candidates must be reviewed before official scoring.", { x: 52, y: 122, size: 9, font, color: rgb(0.55, 0.32, 0.05) });

  const bytes = await pdf.save();
  return new NextResponse(Buffer.from(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="Bay-Baby-PrimusGFS-v4-Audit-Packet.pdf"`,
    },
  });
}
