import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function POST(request: Request) {
  const body = await request.json();
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const page = pdf.addPage([612, 792]);
  page.drawRectangle({ x: 0, y: 700, width: 612, height: 92, color: rgb(0.04, 0.18, 0.14) });
  page.drawText("BAY BABY PRODUCE", { x: 52, y: 747, size: 12, font: bold, color: rgb(0.72, 0.9, 0.69) });
  page.drawText("Primus Audit Packet", { x: 52, y: 718, size: 25, font: bold, color: rgb(1, 1, 1) });
  page.drawText(`${body.startDate ?? "May 22, 2026"} to ${body.endDate ?? "June 22, 2026"}`, { x: 52, y: 660, size: 16, font: bold });
  page.drawText(`Generated by ${body.generatedBy ?? "Juan Diaz"} • ${new Date().toLocaleDateString("en-US")}`, { x: 52, y: 636, size: 10, font, color: rgb(0.35, 0.38, 0.37) });
  const lines = [
    ["Reports included", String(body.count ?? 32)],
    ["Reviewed and approved", "24"],
    ["Still in review", "6"],
    ["Needs attention", "2"],
    ["Readiness", "78%"],
  ];
  let y = 560;
  for (const [label, value] of lines) {
    page.drawText(label, { x: 52, y, size: 12, font });
    page.drawText(value, { x: 430, y, size: 13, font: bold, color: rgb(0.07, 0.38, 0.2) });
    page.drawLine({ start: { x: 52, y: y - 12 }, end: { x: 560, y: y - 12 }, thickness: 0.5, color: rgb(0.82, 0.84, 0.82) });
    y -= 55;
  }
  page.drawText("Packet sections", { x: 52, y: 245, size: 15, font: bold });
  page.drawText("Audit summary  •  Report index  •  Exceptions and corrective actions", { x: 52, y: 218, size: 11, font });
  page.drawText("Full reports grouped by type  •  Attachment appendix  •  Review log", { x: 52, y: 198, size: 11, font });
  const bytes = await pdf.save();
  return new NextResponse(Buffer.from(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="Bay-Baby-Primus-Audit-Packet_2026-05-22_to_2026-06-22.pdf"`,
    },
  });
}
